version: '3.1'

services:

  fcrepo:
    build:
      context: ./fcrepo/4.7.5
    image: oapass/fcrepo:4.7.5-3.4-2@sha256:581f71675a1adab1568ea1924f8a83df974b228c3fd6181f83fbd157bab806d9
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}"
    networks:
      - front
      - back
    volumes:
      - passdata:/data
    depends_on:
      - assets
      - activemq

  activemq:
    build:
      context: ./activemq
    image: oapass/activemq:20200219@sha256:e2351a4ce0d55fd7f016aeca37d789288dc8805fe8bf082b5ede28f7c18e5027
    container_name: activemq
    env_file: .env
    ports:
      - "${ACTIVEMQ_JMS_PORT}:${ACTIVEMQ_JMS_PORT}"
      - "${ACTIVEMQ_STOMP_PORT}:${ACTIVEMQ_STOMP_PORT}"
      - "${ACTIVEMQ_WEBCONSOLE_PORT}:${ACTIVEMQ_WEBCONSOLE_PORT}"
    networks:
      - front
      - back

  ember:
    build:
      context: ./ember
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
        POLICY_SERVICE_URL: "${POLICY_SERVICE_URL}"
        USER_SERVICE_URL: "${USER_SERVICE_URL}"
        DOI_SERVICE_URL: "${DOI_SERVICE_URL}"
        METADATA_SCHEMA_URI: "${METADATA_SCHEMA_URI}"
        MANUSCRIPT_SERVICE_LOOKUP_URL: "${MANUSCRIPT_SERVICE_LOOKUP_URL}"
        MANUSCRIPT_SERVICE_DOWNLOAD_URL: "${MANUSCRIPT_SERVICE_DOWNLOAD_URL}"
    image: oapass/ember:20200512-08b32ec2@sha256:cadb40e3924625bb8737ee0d7f607c712e7dc5ed5fcff7fdae3900a231598098
    container_name: ember
    env_file: .env
    networks:
      - back

  static-html:
    build:
      context: ./static-html
      args:
        STATIC_HTML_GIT_REPO: "${STATIC_HTML_GIT_REPO}"
        STATIC_HTML_GIT_BRANCH: "${STATIC_HTML_GIT_BRANCH}"
    image: oapass/static-html:jhu-20200513-8666f05@sha256:be3eba2c1a02b1a0ee9c708d00454fb7df1651b886f2ea1d643c062acd1ecf06
    container_name: static-html
    env_file: .env
    ports:
      - "${STATIC_HTML_PORT}:${STATIC_HTML_PORT}"
    networks:
      - back
      - front

  ftpserver:
    build: ./ftpserver/0.0.1-demo
    image: oapass/ftpserver@sha256:145f7e3bb494deeb1e1c587f34f0f54649f22d6ef0c107bacd022b0308146ddb
    container_name: ftpserver
    env_file: .env
    ports:
      - "${FTP_PORT}:${FTP_PORT}"
      - "30000-30010:30000-30010"
    networks:
      - front
      - back

  proxy:
    build: ./httpd-proxy/
    image: oapass/httpd-proxy:20200507@sha256:e8ad2e759fe270998efc80bdcacbeb3f965b4b83d875478e36b0ce4c104bb2d3
    container_name: proxy
    networks:
     - front
     - back
    ports:
     - "80:80"
     - "443:443"

  idp:
    build:
      context: ./idp
      args:
        TENANT: jhu
    image: oapass/idp:20190813-jhu@sha256:f7a37180964e0e90e1db15440846a39c39659f20999a11c556b99f43d65c7fcb
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer

  ldap:
    build:
      context: ./ldap
      args:
        TENANT: jhu
    image: oapass/ldap:20190813-jhu@sha256:a5547be7962dabfaff604475e20001f631ad2450a21590bd0a3bd68b3e976b94
    container_name: ldap
    networks:
     - back

  sp:
    build: ./sp/2.6.1
    image: oapass/sp:20200507@sha256:03d652dc51adf919f6f6982bbb5b32188bd8a8053600271dfe0cf9022c2d31fd
    container_name: sp
    networks:
     - back
    secrets:
     - source: sp_key

  dspace:
    build: ./dspace/6.2
    image: oapass/dspace:20200419@sha256:99df12f10846f2a2d62058cf4eef631393d7949a343b233a9e487d54fd82a483
    container_name: dspace
    env_file: .env
    ports:
      - "${DSPACE_PORT}:${DSPACE_PORT}"
    networks:
      back:
        aliases:
          - pass

  postgres:
    build: ./postgres/10.3
    image: oapass/postgres@sha256:a16b49990b5ee111efdbce63eefa4a56ae1257d16114ecaeb584117074deefaa
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - back

  indexer:
    build: ./indexer/0.0.18-SNAPSHOT
    image: oapass/indexer:0.0.18-3.4-1@sha256:3375ea702e0a1c7a5e0e7e06635d28e49af436aeb1c3d88a03d4cb494d7b40bf
    container_name: indexer
    env_file: .env
    networks:
      - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3@sha256:ccfad77c0731c010e6ff8c43b4ab50f5ce90c0fa4e65846530779c5c6707c20a
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - passdata:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:${ES_PORT}"
    networks:
      - front
      - back
    depends_on:
      - assets

  assets:
    image: birkland/assets:2019-04-08_3.4@sha256:7ec44bd52d7cf635ad05a3f509cf7439e187b7768b8a05abae81b49744ec9d5f
    build: ./assets
    volumes:
      - passdata:/data

  #bootstrap:
  #  image: oapass/bootstrap
  #  build: ./bootstrap
  #  container_name: bootstrap
  #  networks:
  #    - back

  deposit:
    build:
      context: ./deposit-services
      args:
        # The providers image is released by the github.com/oa-pass/jhu-package-providers repository
        PROVIDERS_IMAGE: oapass/deposit-services-providers:0.0.2@sha256:8a1aac5b188c5923d68dd520f6d9679bba66ac7ad64761f2b4c4f7f751e113f3
    image: oapass/deposit-pass-docker:1.0.1-3.4@sha256:748b1815ac3b4a1557e305f0d3a2421cc9da6d837a1b6a2699a48214f11824b8
    container_name: deposit
    env_file: .env
    environment:
      - PASS_DEPOSIT_REPOSITORY_CONFIGURATION=file:/repositories-jhu.json
    ports:
      - "${DEPOSIT_DEBUG_PORT}:5007"
    networks:
      - back
    links:
      - dspace:pass.local
# To override configuration, create a file named './repositories.json', edit to suit, and uncomment below
#    volumes:
#      - ./packagers.properties:/packagers.properties


  authz:
    build: ./authz
    image: oapass/authz:0.4.5-3.4@sha256:5ef2579e8094a3eb86d3765a6c910c8ce86a3a0352f821e751d647b4d97c5cc1
    container_name: authz
    env_file: .env
    networks:
      - back

  mail:
    image: oapass/docker-mailserver:20181105@sha256:4dc4d836cfd5fbcbc7819a2f1195366e0fb5d0436b4d632f6a14b9251766a6b3
    hostname: mail
    domainname: jhu.edu
    container_name: mail
    networks:
      - back
    ports:
      - "${MAIL_SMTP}:25"
      - "${MAIL_IMAPS}:993"
      - "${MAIL_MSP}:587"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./mail/config/:/tmp/docker-mailserver/
    env_file: .env
    depends_on:
      - ldap

  notification:
    build: notification-services/0.0.2-3.2
    image: oapass/notification-services:0.0.2-3.2-1@sha256:5475490671d2c630f89265c44736f74d4520b84cf5b239c29b5c74678762a2e9
    container_name: notification
    networks:
      - back
    ports:
      - "${NOTIFICATION_DEBUG_PORT}:5011"
    env_file: .env
    environment:
      - PASS_NOTIFICATION_CONFIGURATION=file:/notification.json

  schemaservice:
    image: oapass/schema-service:v0.6.1-3-gaa6d2f8@sha256:127b8b640b2c4669a6ca89f52677b54997bf0ea32a5e5f5d3e386537d3cf1e68
    container_name: schemaservice
    env_file: .env
    ports:
      - "${SCHEMA_SERVICE_PORT}:${SCHEMA_SERVICE_PORT}"
    networks:
      - front
      - back

  policyservice:
    image: oapass/policy-service:v0.1.2@sha256:b361bc7dd9d366465f7683052e038e5ec93ef77a48e69176590c84044ce7d804
    container_name: policyservice
    env_file: .env
    ports:
      - "${POLICY_SERVICE_PORT}:${POLICY_SERVICE_PORT}"
    networks:
      - front
      - back

  doiservice:
    image: oapass/doi-service:version1.0.0@sha256:a82a1b60b4bae17b9a5628ed3d65501000d576ef3ba6bc3ffe4cbf9138eba82d
    container_name: doiservice
    env_file: .env
    ports:
      - "${PASS_DOI_SERVICE_PORT}:8080"
    networks:
      - front
      - back
  
  downloadservice:
    image: oapass/download-service:v1.0.2@sha256:53312fcca42a87668a46b34500f7f0153d65fdc5535df1dace755ad6bb3d90ba
    container_name: downloadservice
    env_file: .env
    ports:
      - "${DOWNLOAD_SERVICE_PORT}:${DOWNLOAD_SERVICE_PORT}"
    networks:
      - front
      - back

volumes:
  passdata:
    driver: local
  mailstate:
    driver: local
  maildata:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
