version: '3.1'

services:

  fcrepo:
    build:
      context: ./fcrepo/4.7.5
    image: oapass/fcrepo:4.7.5-3.4@sha256:3e39b01edf56c149279cfc51b647df335c01f9ec38036f1724f337ae35d68fe8
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}"
    networks:
      - front
      - back
    volumes:
      - passdata:/data
    depends_on: 
      - assets
      - activemq

  activemq:
    build:
      context: ./activemq
    image: oapass/activemq:20180618@sha256:e3cd47a1bc4c21899fc34e5ac7198f6c069f4148296bad0ce619cc2bdda5f435
    container_name: activemq
    env_file: .env
    ports:
      - "${ACTIVEMQ_JMS_PORT}:${ACTIVEMQ_JMS_PORT}"
      - "${ACTIVEMQ_STOMP_PORT}:${ACTIVEMQ_STOMP_PORT}"
      - "${ACTIVEMQ_WEBCONSOLE_PORT}:${ACTIVEMQ_WEBCONSOLE_PORT}"
    networks:
      - front
      - back

  ember:
    build:
      context: ./ember
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    image: oapass/ember:20181220-5a50f87@sha256:fbc6379cd3ad03fdc6f87b3c46cef1bf0d0b0e5987e76f92c8079d87a8980af7
    container_name: ember
    env_file: .env
    networks:
      - back

  static-html:
    build:
      context: ./static-html
      args:
        STATIC_HTML_GIT_REPO: "${STATIC_HTML_GIT_REPO}"
        STATIC_HTML_GIT_BRANCH: "${STATIC_HTML_GIT_BRANCH}"
    image: oapass/static-html:20181116-4ab9eb3@sha256:2c5a8f315783ab41205aaead6c82c6148f9d6334b1dc33b7bf31033cf008d2d6
    container_name: static-html
    env_file: .env
    ports:
      - "${STATIC_HTML_PORT}:${STATIC_HTML_PORT}"
    networks:
      - back
      - front

  ftpserver:
    build: ./ftpserver/0.0.1-demo
    image: oapass/ftpserver@sha256:145f7e3bb494deeb1e1c587f34f0f54649f22d6ef0c107bacd022b0308146ddb
    container_name: ftpserver
    env_file: .env
    ports:
      - "${FTP_PORT}:${FTP_PORT}"
      - "30000-30010:30000-30010"
    networks:
      - front
      - back

  proxy:
    build: ./httpd-proxy/
    image: oapass/httpd-proxy:20190306@sha256:63770ee48bfaf251565b2e3ffd593284ed3783ef1b1c44390a60d57c9764009c
    container_name: proxy
    networks:
     - front
     - back
    ports:
     - "80:80"
     - "443:443"

  idp:
    build: ./idp/3.3.2
    image: oapass/idp:20181012@sha256:59d920bd4c6a51d12c0961717f38d743710f1bd8221c2b6c8dda6746ac224d7b
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer

  ldap:
    build: ./ldap/
    image: oapass/ldap:20181106@sha256:065b91e74de5565df7d4459590c51986368ee157f73d81eb10232c7dadcb98e4
    container_name: ldap
    networks:
     - back

  sp:
    build: ./sp/2.6.1
    image: oapass/sp:20190306@sha256:6df4a3307fcee68c3f9b1e7fecaa58c0357da1713450a63173ab8a2c79cf14d5
    container_name: sp
    networks:
     - back
    secrets:
     - source: sp_key

  dspace:
    build: ./dspace/6.2
    image: oapass/dspace@sha256:8b1482a4b8ac31fc656ada66184a7a48e0a0e5dfbcf9aacbe308956f25828abf
    container_name: dspace
    env_file: .env
    ports:
      - "${DSPACE_PORT}:${DSPACE_PORT}"
    networks:
      back:
        aliases:
          - pass

  postgres:
    build: ./postgres/10.3
    image: oapass/postgres@sha256:a16b49990b5ee111efdbce63eefa4a56ae1257d16114ecaeb584117074deefaa
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - back

  indexer:
    build: ./indexer/0.0.18-SNAPSHOT
    image: oapass/indexer:0.0.18-3.4@sha256:e51092a9d433219d52207f1ec3f5ea7c652d51f516bcbe9434dae556b921546d
    container_name: indexer
    env_file: .env
    networks:
      - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3@sha256:ccfad77c0731c010e6ff8c43b4ab50f5ce90c0fa4e65846530779c5c6707c20a
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - passdata:/usr/share/elasticsearch/data   
    ports: 
      - "${ES_PORT}:${ES_PORT}"
    networks:
      - front
      - back
    depends_on: 
      - assets

  assets:
    image: birkland/assets:2019-04-08_3.4@sha256:a86764c153cd5e1876fa90b648de39f018d056ee30df991c429893a8ba036d6a
    build: ./assets
    volumes:
      - passdata:/data
  
  #bootstrap:
  #  image: oapass/bootstrap
  #  build: ./bootstrap
  #  container_name: bootstrap
  #  networks:
  #    - back

  deposit:
    build: ./deposit-services/0.1.0-3.2
    image: oapass/deposit-services:0.1.0-3.2-1@sha256:fbe0f70af890ab97a0b2ab6c8d3ad058f7117d81c029b0a1980d037e9a7adc33
    container_name: deposit
    env_file: .env
    environment:
      - PASS_DEPOSIT_REPOSITORY_CONFIGURATION=file:/repositories.json
    ports:
      - "${DEPOSIT_DEBUG_PORT}:5007"
    networks:
      - back
    links:
      - dspace:pass.local
# To override configuration, create a file named './repositories.json', edit to suit, and uncomment below
#    volumes:
#      - ./packagers.properties:/packagers.properties
    links:
      - dspace:pass.local

  authz:
    build: ./authz
    image: oapass/authz:0.4.3-3.2@sha256:8739851bee894a77d207e420fe86b64b6df1fd02f17cbcc60275513026d13f3d
    container_name: authz
    env_file: .env
    networks:
      - back

  mail:
    image: oapass/docker-mailserver:20181105@sha256:4dc4d836cfd5fbcbc7819a2f1195366e0fb5d0436b4d632f6a14b9251766a6b3
    hostname: mail
    domainname: jhu.edu
    container_name: mail
    networks:
      - back
    ports:
      - "${MAIL_SMTP}:25"
      - "${MAIL_IMAPS}:993"
      - "${MAIL_MSP}:587"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./mail/config/:/tmp/docker-mailserver/
    env_file: .env
    depends_on:
      - ldap

  notification:
    build: notification-services/0.0.2-3.2
    image: oapass/notification-services:0.0.2-3.2@sha256:7a693ce4005c88bdf93104d1cea1caec569dbb994ad8eaa07150dcd815a0e002
    container_name: notification
    networks:
      - back
    ports:
      - "${NOTIFICATION_DEBUG_PORT}:5011"
    env_file: .env
    environment:
      - PASS_NOTIFICATION_CONFIGURATION=file:/notification.json

  schemaservice:
    image: oapass/schema-service:v0.1.1
    container_name: schemaservice
    env_file: .env
    ports:
      - "${SCHEMA_SERVICE_PORT}:${SCHEMA_SERVICE_PORT}"
    networks:
      - front
      - back

volumes:
  passdata:
    driver: local
  mailstate:
    driver: local
  maildata:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
