version: '3.1'

services:

  fcrepo:
    build:
      context: ./fcrepo/4.7.5-SNAPSHOT
    image: oapass/fcrepo:4.7.5-2.2-SNAPSHOT-3
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_JMS_PORT}:${FCREPO_JMS_PORT}"
      - "${FCREPO_STOMP_PORT}:${FCREPO_STOMP_PORT}"
      - "${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}"
    networks:
      - front
      - back
    volumes:
      - passdata:/data
    depends_on: 
      - assets

  ember:
    build:
      context: ./ember
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    image: oapass/ember:20180606-902695a
    container_name: ember
    env_file: .env
    ports:
      - "${EMBER_PORT}:${EMBER_PORT}"
    networks:
      - back

  ftpserver:
    build: ./ftpserver/0.0.1-demo
    image: oapass/ftpserver
    container_name: ftpserver
    env_file: .env
    ports:
      - "${FTP_PORT}:${FTP_PORT}"
    networks:
      - front

  proxy:
    build: ./httpd-proxy/
    image: oapass/httpd-proxy:20180608
    container_name: proxy
    networks:
     - front
     - back
    ports:
     - "80:80"
     - "443:443"

  idp:
    build: ./idp/3.3.2
    image: oapass/idp:20180518
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer

  ldap:
    build: ./ldap/
    image: oapass/ldap:20180608
    container_name: ldap
    networks:
     - back

  sp:
    build: ./sp/2.6.1
    image: oapass/sp:20180518
    container_name: sp
    networks:
     - back
    secrets:
     - source: sp_key

  dspace:
    build: ./dspace/6.2
    image: oapass/dspace
    container_name: dspace
    env_file: .env
    ports:
      - "${DSPACE_PORT}:${DSPACE_PORT}"
    networks:
      back:
        aliases:
          - pass

  postgres:
    build: ./postgres/10.3
    image: oapass/postgres
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - back

  indexer:
    build: ./indexer/0.0.10-SNAPSHOT
    image: oapass/indexer:0.0.10-2.2-SNAPSHOT
    container_name: indexer
    env_file: .env
    networks:
      - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - passdata:/usr/share/elasticsearch/data   
    ports: 
      - "${ES_PORT}:${ES_PORT}"
    networks:
      - front
      - back
    depends_on: 
      - assets

  assets:
    image: birkland/assets:2018-06-05
    build: ./assets
    volumes:
      - passdata:/data
  
  #bootstrap:
  #  image: oapass/bootstrap
  #  build: ./bootstrap
  #  container_name: bootstrap
  #  networks:
  #    - back

  deposit:
    build: ./deposit-services/0.0.3-2.2
    image: oapass/deposit-services:0.0.3-2.2
    container_name: deposit
    env_file: .env
    ports:
      - "${DEPOSIT_DEBUG_PORT}:5007"
    networks:
      - back

volumes:
  passdata:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
