version: '3.1'

services:

  fcrepo:
    build:
      context: ./fcrepo/4.7.5-SNAPSHOT
    image: oapass/fcrepo:4.7.5-2.3-SNAPSHOT-1@sha256:a03008e5c4517a6256712963df47b9bf3540318fb95ca26731775c6c26f22105
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}"
    networks:
      - front
      - back
    volumes:
      - passdata:/data
    depends_on: 
      - assets
      - activemq

  activemq:
    build:
      context: ./activemq
    image: oapass/activemq:20180618@sha256:e3cd47a1bc4c21899fc34e5ac7198f6c069f4148296bad0ce619cc2bdda5f435
    container_name: activemq
    env_file: .env
    ports:
      - "${ACTIVEMQ_JMS_PORT}:${ACTIVEMQ_JMS_PORT}"
      - "${ACTIVEMQ_STOMP_PORT}:${ACTIVEMQ_STOMP_PORT}"
      - "${ACTIVEMQ_WEBCONSOLE_PORT}:${ACTIVEMQ_WEBCONSOLE_PORT}"
    networks:
      - front
      - back

  ember:
    build:
      context: ./ember
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    image: oapass/ember:20181011-775220d@sha256:fd57c1c94562b650343df72b75104000869ccd9b99d90dab69930782396d17f6
    container_name: ember
    env_file: .env
    networks:
      - back

  static-html:
    build:
      context: ./static-html
      args:
        STATIC_HTML_GIT_REPO: "${STATIC_HTML_GIT_REPO}"
        STATIC_HTML_GIT_BRANCH: "${STATIC_HTML_GIT_BRANCH}"
    image: oapass/static-html:20180816-23df535@sha256:556085172c39877c4167a92c7464d595b9bbb48da2abae6a8f6377a79429c22e
    container_name: static-html
    env_file: .env
    ports:
      - "${STATIC_HTML_PORT}:${STATIC_HTML_PORT}"
    networks:
      - back
      - front

  ftpserver:
    build: ./ftpserver/0.0.1-demo
    image: oapass/ftpserver@sha256:145f7e3bb494deeb1e1c587f34f0f54649f22d6ef0c107bacd022b0308146ddb
    container_name: ftpserver
    env_file: .env
    ports:
      - "${FTP_PORT}:${FTP_PORT}"
      - "30000-30010:30000-30010"
    networks:
      - front
      - back

  proxy:
    build: ./httpd-proxy/
    image: oapass/httpd-proxy:20180815@sha256:f2aeead1df34ddb8d22b8251a7ef2542f7aedb75952c57a8caecf4c74fd79bb7
    container_name: proxy
    networks:
     - front
     - back
    ports:
     - "80:80"
     - "443:443"

  idp:
    build: ./idp/3.3.2
    image: oapass/idp:20180815@sha256:8cb8e3ac890200bd1611b1b9c82e3cebf7ace1007e5cdfab36eab3118f70be6b
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer

  ldap:
    build: ./ldap/
    image: oapass/ldap:201808706@sha256:89cdbc3e91917675d9e3da94447f05b74a8fa0b018965c8d97ff278273ab7971
    container_name: ldap
    networks:
     - back

  sp:
    build: ./sp/2.6.1
    image: oapass/sp:20180815@sha256:2882114242a7f3160605b3e0f0adfc348f5b74fe625e1eae8db1bb034200c2a8
    container_name: sp
    networks:
     - back
    secrets:
     - source: sp_key

  dspace:
    build: ./dspace/6.2
    image: oapass/dspace@sha256:8b1482a4b8ac31fc656ada66184a7a48e0a0e5dfbcf9aacbe308956f25828abf
    container_name: dspace
    env_file: .env
    ports:
      - "${DSPACE_PORT}:${DSPACE_PORT}"
    networks:
      back:
        aliases:
          - pass

  postgres:
    build: ./postgres/10.3
    image: oapass/postgres@sha256:a16b49990b5ee111efdbce63eefa4a56ae1257d16114ecaeb584117074deefaa
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - back

  indexer:
    build: ./indexer/0.0.13-SNAPSHOT
    image: oapass/indexer:0.0.13-2.3-SNAPSHOT@sha256:d5212abb080cd455c6482110e70727e08ba6fa3046249e2d7e6186a1be1fcfb8
    container_name: indexer
    env_file: .env
    networks:
      - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3@sha256:ccfad77c0731c010e6ff8c43b4ab50f5ce90c0fa4e65846530779c5c6707c20a
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - passdata:/usr/share/elasticsearch/data   
    ports: 
      - "${ES_PORT}:${ES_PORT}"
    networks:
      - front
      - back
    depends_on: 
      - assets

  assets:
    image: birkland/assets:2018-10-09@sha256:583fcbc5b44a447aeb637974191912ff41ed34d5c516f12b1a87fd855504c911
    build: ./assets
    volumes:
      - passdata:/data
  
  #bootstrap:
  #  image: oapass/bootstrap
  #  build: ./bootstrap
  #  container_name: bootstrap
  #  networks:
  #    - back

  deposit:
    build: ./deposit-services/0.0.9-2.3
    image: oapass/deposit-services:0.0.9-2.3@sha256:52ddd80ae45b09ee25ec9eedd4fca450b9d3fa230b97aec7206f9dad1702988f
    container_name: deposit
    env_file: .env
    environment:
      - PASS_DEPOSIT_REPOSITORY_CONFIGURATION=file:/repositories.json
    ports:
      - "${DEPOSIT_DEBUG_PORT}:5007"
    networks:
      - back
    links:
      - dspace:pass.local
# To override configuration, create a file named './repositories.json', edit to suit, and uncomment below
#    volumes:
#      - ./repositories.json:/repositories.json

  authz:
    build: ./authz
    image: oapass/authz:0.2.1-2.3-SNAPSHOT@sha256:b8eca98c4cece4b0eb6df7024eb6bdebff8bc311942f098813cc077d025f08d3
    container_name: authz
    env_file: .env
    networks:
      - back

volumes:
  passdata:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
