version: '3.1'

services:

  fcrepo:
    build:
      context: ./fcrepo/4.7.5-SNAPSHOT
    image: oapass/fcrepo:4.7.5-2.2-SNAPSHOT-10@sha256:fef548b284f4a52bfe6530b8295f6dadd4f3cfe1ed330c564983a7382fd832d0
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}"
    networks:
      - front
      - back
    volumes:
      - passdata:/data
    depends_on: 
      - assets
      - activemq

  activemq:
    build:
      context: ./activemq
    image: oapass/activemq:20180618@sha256:e3cd47a1bc4c21899fc34e5ac7198f6c069f4148296bad0ce619cc2bdda5f435
    container_name: activemq
    env_file: .env
    ports:
      - "${ACTIVEMQ_JMS_PORT}:${ACTIVEMQ_JMS_PORT}"
      - "${ACTIVEMQ_STOMP_PORT}:${ACTIVEMQ_STOMP_PORT}"
      - "${ACTIVEMQ_WEBCONSOLE_PORT}:${ACTIVEMQ_WEBCONSOLE_PORT}"
    networks:
      - front
      - back

  ember:
    build:
      context: ./ember
      args:
        EMBER_GIT_REPO: "${EMBER_GIT_REPO}"
        EMBER_GIT_BRANCH: "${EMBER_GIT_BRANCH}"
    image: oapass/ember:20180625-a236157@sha256:9a0cdd531d2a0fff9b7a2c788b690befe2ca14ddcbaa188e1428f77b2667594c
    container_name: ember
    env_file: .env
    networks:
      - back

  static-html:
    build:
      context: ./static-html
      args:
        STATIC_HTML_GIT_REPO: "${STATIC_HTML_GIT_REPO}"
        STATIC_HTML_GIT_BRANCH: "${STATIC_HTML_GIT_BRANCH}"
    image: oapass/static-html:20180625-e2a4717@sha256:515be2360ca9e22b3ecbfee9ccdc4700af9e74764cfa0128fa8e96820c17b367
    container_name: static-html
    env_file: .env
    ports:
      - "${STATIC_HTML_PORT}:${STATIC_HTML_PORT}"
    networks:
      - back
      - front

  ftpserver:
    build: ./ftpserver/0.0.1-demo
    image: oapass/ftpserver@sha256:145f7e3bb494deeb1e1c587f34f0f54649f22d6ef0c107bacd022b0308146ddb
    container_name: ftpserver
    env_file: .env
    ports:
      - "${FTP_PORT}:${FTP_PORT}"
      - "30000-30010:30000-30010"
    networks:
      - front
      - back

  proxy:
    build: ./httpd-proxy/
    image: oapass/httpd-proxy:20180622@sha256:423b358d177cb903316b1449ed2d25357137e85a9b3f4d270e30e56354c54c0e
    container_name: proxy
    networks:
     - front
     - back
    ports:
     - "80:80"
     - "443:443"

  idp:
    build: ./idp/3.3.2
    image: oapass/idp:20180518@sha256:8fc230e81574161626c8cebd9fda35ae2ff0f8a0c8bce085397972ecb09ce7eb
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer

  ldap:
    build: ./ldap/
    image: oapass/ldap:20180625@sha256:91775d0aa6ed7767aa25345355cea22c9136a8be4dac564ecc9c44870ab00af5
    container_name: ldap
    networks:
     - back

  sp:
    build: ./sp/2.6.1
    image: oapass/sp:20180618@sha256:6999dc7a46c3fd3710bb215d562aca12463e8366eead899ec633b84e1456af3a
    container_name: sp
    networks:
     - back
    secrets:
     - source: sp_key

  dspace:
    build: ./dspace/6.2
    image: oapass/dspace@sha256:8b1482a4b8ac31fc656ada66184a7a48e0a0e5dfbcf9aacbe308956f25828abf
    container_name: dspace
    env_file: .env
    ports:
      - "${DSPACE_PORT}:${DSPACE_PORT}"
    networks:
      back:
        aliases:
          - pass

  postgres:
    build: ./postgres/10.3
    image: oapass/postgres@sha256:a16b49990b5ee111efdbce63eefa4a56ae1257d16114ecaeb584117074deefaa
    container_name: postgres
    env_file: .env
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    networks:
      - back

  indexer:
    build: ./indexer/0.0.12-SNAPSHOT
    image: oapass/indexer:0.0.12-2.2-SNAPSHOT@sha256:a8599b27219d9cb85b596fd90d173e370c3d53494630a98c00bee43f5c7bd8e6
    container_name: indexer
    env_file: .env
    networks:
      - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3@sha256:ccfad77c0731c010e6ff8c43b4ab50f5ce90c0fa4e65846530779c5c6707c20a
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - passdata:/usr/share/elasticsearch/data   
    ports: 
      - "${ES_PORT}:${ES_PORT}"
    networks:
      - front
      - back
    depends_on: 
      - assets

  assets:
    image: birkland/assets:2018-06-24@sha256:3f2214373afe1791235487e153f58c4c3e4f4788a9d2d9ef35d6f8ca2a41bbbb
    build: ./assets
    volumes:
      - passdata:/data
  
  #bootstrap:
  #  image: oapass/bootstrap
  #  build: ./bootstrap
  #  container_name: bootstrap
  #  networks:
  #    - back

  deposit:
    build: ./deposit-services/0.0.6-2.2
    image: oapass/deposit-services:0.0.6-2.2-2@sha256:f850cb53b973c8ac1e1e1fe45e06ab9adaf31aa6b4f801d4a19b01ae86eeaf9f
    container_name: deposit
    env_file: .env
    environment:
      - PASS_DEPOSIT_TRANSPORT_CONFIGURATION=file:/packagers.properties
    ports:
      - "${DEPOSIT_DEBUG_PORT}:5007"
    networks:
      - back
# To override packager configuration, create a file named './packagers.properties', edit to suit, and uncomment below
#    volumes:
#      - ./packagers.properties:/packagers.properties

  authz:
    build: ./authz
    image: oapass/authz:0.1.0-2.2-SNAPSHOT@sha256:7b82b6a348794f5aff4b91a90dcfcbeb1a8fbffee6a7e1bd337f12909480a86f
    container_name: authz
    env_file: .env
    networks:
      - back
  
  testing:
    image: oapass/test:20180625@sha256:15b9a579eb46cfaf823334564078feb1d9f722a32fefb37073b7cd9081cd21f8
    build: ./testing
    env_file: .env
    networks:
      - back

volumes:
  passdata:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
