apiVersion: v1
data:
  idp-sealer: zs7OzgAAAAIAAAABAAAAAwAHc2VjcmV0MQAAAVGO1vtFrO0ABXNyADNjb20uc3VuLmNyeXB0by5wcm92aWRlci5TZWFsZWRPYmplY3RGb3JLZXlQcm90ZWN0b3LNV8pZ5zC7UwIAAHhyABlqYXZheC5jcnlwdG8uU2VhbGVkT2JqZWN0PjY9psO3VHACAARbAA1lbmNvZGVkUGFyYW1zdAACW0JbABBlbmNyeXB0ZWRDb250ZW50cQB+AAJMAAlwYXJhbXNBbGd0ABJMamF2YS9sYW5nL1N0cmluZztMAAdzZWFsQWxncQB+AAN4cHVyAAJbQqzzF/gGCFTgAgAAeHAAAAAPMA0ECDF05gzqechhAgEUdXEAfgAFAAAAkCcYfeq195wKq/J23gnYHYs4chtCxEfOtZ8zAKGFHcuo/Z1VA54vM1LYs0JGbUqBVzMITyowxzwIPDn80KUcRlS820GNBFLWHAP+I9ci3xTxkgivOTo5f6UoRRgprxhBD3CEh+95ANcIAuS3uPUzCOvPZYM9M2b0LvYqszCKn62I2xudt5C7rWSdBMrg/z51QXQAFlBCRVdpdGhNRDVBbmRUcmlwbGVERVN0ABZQQkVXaXRoTUQ1QW5kVHJpcGxlREVTgJQ2TpM9nXDxvlyM1sl0IyodVio=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: idp-sealer
  name: idp-sealer
type: Opaque
