name: Deploy passdemo

on: workflow_dispatch

jobs:
  deploy_code:
     runs-on: passdemo
     steps:
      - uses: actions/checkout@v2

      - name: Sanity Check
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }}"
          pwd
          git log -1
