name: Deploy passdemo

on: workflow_dispatch

jobs:
  deploy_code:
     runs-on: passdemo
     steps:
      - uses: actions/checkout@v2

      - name: Code Sanity Check
        run: |
          echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "üêß This job is now running on a ${{ runner.os }}"
          pwd
          ls -la

      - name: Docker Sanity Check
        run: |
          groups
          docker info

      - name: Stop Existing App
        run: |
          docker-compose down

      - name: Build App
        run: |
          docker-compose pull

      # - name: Run App
      #   run: |
      #     docker-compose up -d
